version: "2"
services:
  mongo:
    container_name: mongoDBCrud
    image: mongo
    ports:
      - "27017:27017"
  app:
    container_name: appCrud
    restart: always
    build: .
    ports:
      - "4000:4000"
    links:
      - mongo    